# standard jekyll configuration

permalink: date
pygments: true
exclude: ['Rakefile', 'README.md', 'config.rb']
markdown: rdiscount

# configuration required for some pages

domain: freeair.io
title: FreeAir
author: FreeAir team (Ikenna Okpala and Seyi Ogunyemi)
email: we@freeair.io

# configuration for ehancements, uncomment to enable

# feedburner:
#   id: feedburnerid

google_analytics:
  account: UA-34835090-1

# github:
#   username: freeair

# disqus:
#   id: disqusid
